### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by banana-zh** [mobilegptsys/MobileGPT#1]
Thank you for sharing your great work! 
I've been trying to run the project on my cellphone(android 14) after installing the App on it according to the readme. 
However, I have encountered a problem that has troubled me for a long time. Every time it goes the 'X' circumstance, after receiving the XML sent by the phone, when the host got the next action and trying to send it to the phone, the socket will be disconnected and the error 'Connection reset by peer' will be reported. Have you encountered similar problems, and do you have any suggestions or solutions to the problem I am currently facing? Thank you again for your good work!

**Comment by sunjae1294** [comment]
I would have to look into the detailed logs to find out what causes the problem. Can you tell us some details about this occurrence? log from MobileGPT app could help. 

Also, does this error only occur for 'X'?

**Comment by banana-zh** [comment]
> I would have to look into the detailed logs to find out what causes the problem. Can you tell us some details about this occurrence? log from MobileGPT app could help.
> 
> Also, does this error only occur for 'X'?

Thank you very much for your response! I have encountered two issues.
Firstly, the problem was a failure to successfully retrieve the app list, as evidenced by the app list being shown as 0 in the first log. I proceeded to bypass this issue by attempting to write fixed app package names.
![2 jpg](https://github.com/mobilegptsys/MobileGPT/assets/129167306/9bb4b8d8-573e-44f1-b461-810a00cfa572)

Secondly, I encountered the disconnect issue as mentioned in the thread, which exclusively occors in 'X' (while everything runs OK under 'L', 'I', and 'S'). The disconnection occur right at the end of the 'X' when sending the action (at line 127 here).
![3 jpg](https://github.com/mobilegptsys/MobileGPT/assets/129167306/19a8fac8-902b-46c4-9655-33e5ee727d56)

Below, I have provided the app log for this issue. I really appreciate your time and look forward to your assistance and further response. Many thanks!
![2 jpg](https://github.com/mobilegptsys/MobileGPT/assets/129167306/09d7ccca-d3fc-4ec2-9a04-bf5e95f6ecd5)

full logs are here below
[problem1.log.txt](https://github.com/user-attachments/files/15973877/problem1.log.txt)
[problem2.log.txt](https://github.com/user-attachments/files/15973878/problem2.log.txt)

**Comment by sunjae1294** [comment]
As for the app list in apps.csv, 

the app list gets initialized when you first install the MobileGPT app and authorize accessibility service to the app.

So that means that you need to have your MobileGPT server running when authorizing the MobileGPT app its accessibility permission.

As for the problem where you get socket disconnection right after sending the first XML file, check your mobile device's settings on the background app's resource usage. Some devices, especially Samsung Galaxy, have a strict policy for apps running in the background. And that could have caused the MobileGPT app to lose network access when it goes into the background.
